import type { Metadata } from "next";
import { Inter, Darker_Grotesque } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const interSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const darkerGrotesque = Darker_Grotesque({
  variable: "--font-darker-grotesque",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable} ${darkerGrotesque.variable} font-sans antialiased`}
        style={{ fontFamily: "var(--font-inter), var(--font-darker-grotesque), sans-serif" }}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
